In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,10,(3,2))
arr.shape
arr

array([[5, 5],
       [3, 1],
       [7, 2]])

In [3]:
arr.reshape(1,6) #cambia la forma del array

array([[6, 8, 9, 9, 8, 2]])

In [6]:
arr.reshape(2,3)

array([[5, 5, 3],
       [1, 7, 2]])

In [7]:
np.reshape(arr,(1,6))

array([[5, 5, 3, 1, 7, 2]])

In [8]:
np.reshape(arr,(2,3),'C') #como lenguaje C, base de Python!

array([[5, 5, 3],
       [1, 7, 2]])

In [9]:
np.reshape(arr,(2,3),'F') #como lenguaje Fortran

array([[5, 7, 1],
       [3, 5, 2]])

In [10]:
np.reshape(arr,(2,3),'A') #como mejor esté optimizado en memoria

array([[5, 5, 3],
       [1, 7, 2]])