In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand() # valor aleatorio entre 0 y 1

0.0050981337635118695

In [11]:
np.random.rand(4)

array([0.62493022, 0.52796693, 0.48510506, 0.43769347])

In [12]:
np.random.rand(4,4)

array([[0.17229926, 0.99090745, 0.59713975, 0.46276996],
       [0.50080499, 0.38969733, 0.85518129, 0.72026533],
       [0.01966763, 0.69180536, 0.88577843, 0.43524948],
       [0.3878286 , 0.35883079, 0.56972915, 0.75989274]])

In [13]:
np.random.randint(1,15)

13

In [14]:
np.random.randint(1,100,(10,10)) # con estructura determinada

array([[40, 37, 32, 40, 41, 25, 86, 41, 65, 33],
       [39, 47, 24, 80, 60, 56, 79, 99, 35, 88],
       [15, 23, 31, 74, 67, 69, 80, 51, 58, 36],
       [ 4, 70,  4, 81, 90, 87, 20, 71, 86, 10],
       [88, 45, 52, 94, 92, 18, 85, 29, 34, 78],
       [84, 36, 44, 30,  9, 24,  5, 86, 21, 14],
       [71, 58, 71, 67, 64, 24, 38, 85, 88, 69],
       [66, 11, 64, 92, 45,  9, 69, 13, 45, 35],
       [27, 19, 22, 35, 42,  2, 95, 51, 16, 94],
       [62, 90, 38, 50, 12, 60, 38, 26, 66, 39]])