Importamos la librería Numpy:

In [1]:
import numpy as np

Forma tradicional de generar una lista:

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

De esta forma la convertimos en array de Numpy:

In [12]:
arr = np.array(lista)
print(arr)
type(arr)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

Acá vemos como declarar una matriz y transformarla en array de Numpy:

In [11]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matrizNp = np.array(matriz)
print(matrizNp)
type(matrizNp)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

Accedemos a cada elemento del array con su índice, de esta manera podemos hacer operaciones matemáticas entre elementos de los arrays:

In [14]:
#indexing
arr
print(arr[0])
print(arr[5])
arr[0] + arr[5]

1
6


7

Para el caso de matrices, el primer índice representa la fila y el segundo la columna. Si indicamos un solo índice, traerá la fila completa:

In [20]:
matriz
print(matrizNp[0])
print(matrizNp[2])
print(matrizNp[0,2])

[1 2 3]
[7 8 9]
3


In [7]:
#slicing (ojo no toma el último valor)
arr[0:3]
arr[1:6]
arr[:6] #arranca desde cero
arr[2:] #arranca de 2 hasta el final
arr[:]
arr[::3] #todo de tres en tres
arr[-1]
arr[-3:]

array([7, 8, 9])

In [8]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])