In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [4]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [5]:
arr #arruinamos el original!!!

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [6]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [7]:
arr #así no afectamos al original y si a una copia suya

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])