In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,20,10)

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[ 7, 11, 13,  3,  4],
       [ 8, 10, 10, 14, 10]])

In [ ]:
arr.max() #máximo del arreglo

14

In [ ]:
matriz.max(0) #por columna

array([ 8, 11, 13, 14, 10])

In [ ]:
matriz.max(1) #por fila

array([13, 14])

In [ ]:
arr.argmax() #índice del más grande

8

In [ ]:
matriz.argmax(0)

array([1, 0, 0, 1, 1])

In [ ]:
arr.min()

3

In [ ]:
matriz.min(0)

array([ 7, 10, 10,  3,  4])

In [ ]:
matriz.min(1)

array([3, 8])

In [ ]:
arr.argmin()

3

In [ ]:
matriz.argmin(1)

array([3, 0])

In [ ]:
arr.ptp()

11

In [ ]:
matriz.ptp()

11

In [ ]:
matriz.ptp(0)

array([ 1,  1,  3, 11,  6])

In [ ]:
np.percentile(arr,50)

10.0

In [ ]:
np.percentile(arr,0)

3.0

In [ ]:
np.percentile(arr,100)

14.0

In [ ]:
arr.sort() #ordena de menor a mayor
arr

array([ 3,  4,  7,  8, 10, 10, 10, 11, 13, 14])

In [ ]:
np.median(arr) #mediana = percentil 50

10.0

In [ ]:
np.median(matriz,0)

array([ 6.5,  7. ,  9. , 10.5, 12. ])

In [ ]:
np.median(matriz,1)

array([ 7., 11.])

In [ ]:
np.std(arr) #desviación estándar

3.3763886032268267

In [ ]:
np.var(arr) #varianza

11.4

In [ ]:
np.std(arr)**2 #desviación estándar al cuadrado = varianza

11.400000000000002

In [ ]:
np.mean(arr) #media

9.0

In [65]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [ ]:
a.ndim

2

In [67]:
b.ndim

1

In [68]:
np.concatenate((a,b),axis=0) #dara error por diferencia de dimensiones

ValueError: ignored

In [69]:
b = np.expand_dims(b,axis=0) #para expandir, igualar dimensiones y poder concatenar

In [70]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
np.concatenate((a,b),axis=1) #dara error por diferencia de dimensiones

ValueError: ignored

In [72]:
np.concatenate((a,b.T),axis=1) #aplica transpuesta para permitir concatenar

array([[1, 2, 5],
       [3, 4, 6]])

In [73]:
b.T

array([[5],
       [6]])