In [2]:
import numpy as np
arr = np.array([1,2,3,4])
arr.dtype #tipo de dato del array

dtype('int64')

In [3]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype
arr #se evidencia el cambio a decimal

array([1., 2., 3., 4.])

In [4]:
arr = np.array([1,2,3,4])
arr = arr.astype(np.float64)
arr #cambio a float

array([1., 2., 3., 4.])

In [5]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr #cambio a bool

array([False,  True,  True,  True,  True])

In [6]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr #cambio a string

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [7]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr #cambio a integer

array([0, 1, 2, 3, 4], dtype=int8)